### ISSUE TITLE
File-locking required for in-place mode exception.

### ISSUE THREAD

**Issue by nalcabio-tom** [replikativ/konserve-redis#4]
I tried each of the latest commits, https://github.com/replikativ/konserve-redis/commit/d4231e6745dbcf57b51024f6cfff90d57d44be0b and https://github.com/replikativ/konserve-redis/commit/6da966b3afc28a606c6ff7cecd514c11d3e42a52, and they both cause the error below. Rolling back to https://github.com/replikativ/konserve-redis/commit/44bc7e459826abbc401afbc7b24a354b5e994cda works.

```
Execution error (ExceptionInfo) at konserve.impl.defaults/connect-default-store (defaults.cljc:472).
You need to activate file-locking for in-place mode.
```

**Comment by whilo** [comment]
My apologies, we are fixing CI/CD again now and I did not have redis at hand yesterday. I have changed the flags now, hopefully the latest release works.

**Comment by nalcabio-tom** [comment]
```
Execution error (IllegalArgumentException) at konserve.protocols/eval20689$fn$G (protocols.cljc:24).
No implementation of method: :-serialize of protocol: #'konserve.protocols/PStoreSerializer found for class: nil
```

**Comment by whilo** [comment]
Typo... my system-wide redis is somehow blocking and not working for the unit tests, I need to check that later. I hope it works now.

**Comment by nalcabio-tom** [comment]
Thanks @whilo. This seems to be working. I have other errors now because of https://github.com/replikativ/datahike/issues/303 but I believe this issue can be closed. Thanks again!
